### ISSUE TITLE
What should be the data type for the response?

### ISSUE THREAD

**Issue by samuelgoto** [WICG/digital-credentials#119]
What should be the WebIDL data type for the [`DigitalCredential.data`](https://wicg.github.io/digital-credentials/#the-digitalcredential-interface) response?

This is currently returning `any` (to [keep](https://github.com/WICG/digital-credentials/pull/107) Safari and Chrome's implementation interoperable), but we should probably be more specific than that.

A few options that occurred to us:

* An `Uint8Array`
* A `DOMString` ([what WebOTP uses](https://wicg.github.io/web-otp/#OTPCredential))
* An `USVString` ([what FedCM uses](https://fedidcg.github.io/FedCM/#browser-api-identity-credential-interface) -- as opposed to a `DOMString` it can take UTF-8, e.g. `application/json`, guidance from TAG [here](https://github.com/whatwg/webidl/issues/84) and [here](https://w3ctag.github.io/design-principles/#idl-string-types)),
* An `ArrayBuffer` ([what WebAuthn is using](https://w3c.github.io/webauthn/#authenticatorresponse), but also apparently [discouraged](https://github.com/w3ctag/design-principles/issues/463))
* A [`Blob`](https://www.w3.org/TR/FileAPI/#dfn-Blob), which has a `text()` and `bytes()` methods (thanks to Joshua Bell for bringing up this suggestion!).
* `object` if everything can be `JSON.parse()`-able

It is not clear to me what are the trade-offs between these options (mostly ergonomics? or are there security trade-offs here?) nor what the requirements are (e.g. do we need to support passing back binary or non-JSON response's data?), so this issue here is intended to try to collect requirements and help us figure out what's best to use.

@marcoscaceres FYI

**Comment by marcoscaceres** [comment]
Use of ArrayBuffer is discouraged, so probably a Uint8Array. See also: 
https://github.com/WICG/digital-credentials/issues/93

And https://github.com/w3ctag/design-principles/issues/463

However, before we settle on something, we need to make sure we fully understand what wallets are going to be returning. 

There's also some overlap with https://github.com/WICG/digital-credentials/issues/95 cc @timcappalli

**Comment by samuelgoto** [comment]
> However, before we settle on something, we need to make sure we fully understand what wallets are going to be returning.

Yeah, agreed that this is the key question. The main question I have on my mind is whether wallets are going to be returning  binary or text (e.g. text/json). I'm assuming wallets are going to be returning small payloads, so we don't need streams.

We should also probably find a way to avoid cornering ourselves doing something that is forwards compatible if we wanted to change the type later.

**Comment by samuelgoto** [comment]
In the CG call today we converged as a group that `object` is the preferred direction, since:

- we heard from @Sakurann that everything coming back from OpenID4VP would be JSON-serializable, so doesn't have to be `Uint8Array`,
- If text can be assumed, `object` is more specific than `DOMString` and `USVString`, as JSON-parseable text

We heard from Lee that the cross-device hybrid/ctap structure also assume that the response can be JSON-parseable/stringifiable, so this aligns well.

@marcoscaceres and I will work towards patching the spec to specify that the response data is of type `object`.
