### ISSUE TITLE
Credential request options mediation requirement

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#147]
The [`CredentialRequestOptions`](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialrequestoptions) dictionary provides [CredentialMediationRequirement](https://w3c.github.io/webappsec-credential-management/#enumdef-credentialmediationrequirement) [mediation](https://w3c.github.io/webappsec-credential-management/#dom-credentialrequestoptions-mediation) that defaults to "optional". 

The other possible values are:

- ["silent"](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-silent),
- ["optional"](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-optional),
- ["conditional"](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional),
- ["required"](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-required)

I think that any call to `.get()` will be [user mediated](https://w3c.github.io/webappsec-credential-management/#user-mediated) (i.e., will show UI). Thus, we should throw a type error for anything but "required" user mitigation.

**Comment by marcoscaceres** [comment]
Related https://github.com/w3c/webappsec-credential-management/issues/248

**Comment by Sakurann** [comment]
(if I understood correctly) what if there is no wallet installed on a user device that can meet verifier's requests? would that still result in user interaction "you don't have a wallet that can fulfill this request?". It actually might be nice if this can lead to a screen where verifier can prompt the user to install wallet(s)?

**Comment by timcappalli** [comment]
> (if I understood correctly) what if there is no wallet installed on a user device that can meet verifier's requests? would that still result in user interaction "you don't have a wallet that can fulfill this request?". It actually might be nice if this can lead to a screen where verifier can prompt the user to install wallet(s)?

That would be the app platform's responsibility / choice. Conditional Mediation provides the ability to provide non-modal experiences for credential requests, such as the autofill UI for passkeys.

**Comment by samuelgoto** [comment]
> would that still result in user interaction "you don't have a wallet that can fulfill this request?". 

Yeah, I think that's what Android is converging to: show a "no credential available" UI. 

> It actually might be nice if this can lead to a screen where verifier can prompt the user to install wallet(s)?

That seems reasonable and worth exploring further.

**Comment by marcoscaceres** [comment]
Yeah, thought that that's outside the scope of the standard... that's gets into platform specific experience stuff.
