### ISSUE TITLE
Rename "providers" to "presentationRequests" or just  "requests"?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#155]
As came up in #71, "providers" might not be the most clear member name to use:

@timcappalli [proposed](https://github.com/WICG/digital-credentials/pull/71#issuecomment-2260675780):

```WebIDL
dictionary DigitalCredentialRequestOptions {
  sequence<DigitalCredentialsPresentationRequest> presentationRequests;
};
```

I'd be ok with just "requests" tho, but `presentationRequests` is also pretty clear.

**Comment by samuelgoto** [comment]
> I'd be ok with just "requests" tho, but presentationRequests is also pretty clear.

I'd prefer something short as `requests` rather than `presentationRequests`, since it it is going to go front and center in the API call:

```javascript
navigator.identity.get({
  digital: {
    presentationRequests: [..]
    requests: [...]
  }
});
```

**Comment by timcappalli** [comment]
`requests` SGTM

**Comment by marcoscaceres** [comment]
Ok, requests it is... will send a PR soon.

**Comment by samuelgoto** [comment]
> Ok, requests it is... will send a PR soon.

Something that we should ponder on is our tolerance to backwards incompatible changes (like this one) and where to draw a line ... this renaming, specifically, will force us to backwards incompatibles changes and propagate it to others, such as here:

https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-request

And here:

https://groups.google.com/a/chromium.org/g/blink-dev/c/ak8HvMr-GR4

I think we are still at a point where we can allow ourselves to make backwards incompatible changes, but I think they will get increasingly more expensive (so the bar for benefits will raise too).

**Comment by marcoscaceres** [comment]
yes, I agree. Let's set TPAC as the date... I think we will have enough implementation experience by then. 

Mindful also that `.identity.` will also go away soon hopefully once we fix https://github.com/w3c/webappsec-credential-management/issues/244

**Comment by samuelgoto** [comment]
> Mindful also that .identity. will also go away soon hopefully once we fix w3c/webappsec-credential-management#244

I didn't get the sense that Mozilla was supportive of that change.

**Comment by marcoscaceres** [comment]
I think we are still discussing? Irrespective of this spec, that change still matters because otherwise the spec is open ended.

**Comment by marcoscaceres** [comment]
@bvandersloot-mozilla, would you mind taking a look at my follow up in the Cred Man issue and see if it makes any sense? I’m still feeling pretty strongly we should have the single entry point, but could be convinced otherwise.

**Comment by samuelgoto** [comment]
> I’m still feeling pretty strongly we should have the single entry point, but could be convinced otherwise.

I expanded a bit where I stand in that thread:

https://github.com/w3c/webappsec-credential-management/issues/244#issuecomment-2297078104
