### ISSUE TITLE
Links to sample code do not work

### ISSUE THREAD

**Issue by huhubi** [WICG/digital-credentials#169]
I am currently reading through the Prototype HOWTO and see that the links of the sample code mentioned at [https://github.com/WICG/digital-credentials/wiki/HOWTO%3A-Try-the-Prototype-API-in-Chrome-Android#how-to-generate-the-response](https://github.com/WICG/digital-credentials/wiki/HOWTO%3A-Try-the-Prototype-API-in-Chrome-Android#how-to-generate-the-response) are currently not working.

+@RByers

**Comment by timcappalli** [comment]
They are currently being updated and moved to digitalcredentials.dev

**Comment by timcappalli** [comment]
@huhubi please see https://digitalcredentials.dev/docs/wallets/android
