### ISSUE TITLE
Update example to show feature detection

### ISSUE THREAD

**Issue by RByers** [WICG/digital-credentials#170]
Now that we're back to using `navigator.credentials`, our simple feature detection mechanism of `if ('identity' in navigator)` won't work. Presumably we'd recommend `if ('DigitalCredential' in window)` instead, right? Perhaps we should add this to the example in the explainer to make it clear? 

I know of one developer who wasn't sure how best to feature-detect our origin trial and so instead looked for a Chrome Android UA string with Chrome version >= 128. Obviously that's not what we want people doing since the API will become available on other browsers too. Our examples should document our best-practice recommendations.

**Comment by timcappalli** [comment]
For passkeys and WebAuthn, we typically recommend:

```js
if ( typeof window.PublicKeyCredential !== 'undefined' ) {
// do stuff
}
```

**Comment by timcappalli** [comment]
@RByers you can probably steal this updated example: https://digitalcredentials.dev/docs/verifier-site/requesting-cred/

**Comment by RByers** [comment]
SGTM, happy to incorpoate something like this into the explainer. Putting on my queue for now, but also happy for someone else to grab it if they get to it before me.
