### ISSUE TITLE
Prioritization of credential providers

### ISSUE THREAD

**Issue by timcappalli** [WICG/digital-credentials#42]
2023-11-01 meeting: add some text about precedence for multiple elements of the request array.

https://github.com/WICG/identity-credential/blob/main/digital-credentials-2-proposal.md

**Comment by tplooker** [comment]
Just adding to this one, a couple of things that were discussed which is probably worth elaborating on

- The providers array or set is expected to be interpreted as a logical XOR. That is a request to this API which features more then one provider is to be interpreted as "please respond with one response matching one of the provider requests".
- This raises a side question on the above which wasn't discussed, can you have a request with multiple providers of the same protocol? I'd assume so.
- When a relying party (website) makes a multi-party request any prioritisation of the providers downstream in handling the request should be user driven through preferences.

**Comment by marcoscaceres** [comment]
Very similar issue came up in Payment Request with respect to the ordering of payment instruments. In practice, it's really the user's preference (in as far as they are able to set a preference and that may be outside the control of the browser, specially if the wallet or wallets are provided by the OS or as native apps)... we should be mindful of the language we use though, as it starts to encroach on UI decisions.

**Comment by timcappalli** [comment]
Thinking about this a bit more, I'm not sure this is something that the web platform API should address. It is ultimately up to the credential selector provided by the app platform to decide the ordering.

**Comment by timcappalli** [comment]
2024-06-26: this would be addressed by the OID4VP layer, and is being discussed in that WG in the context of the new query language

**Comment by timcappalli** [comment]
2024-07-29 call: agreed with [conclusion](https://github.com/WICG/digital-credentials/issues/42#issuecomment-2192745138), closing issue.
