### ISSUE TITLE
Rename repo to "digital-credentials"

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#55]
Given that we found that "identity credentials" had been squatted by another spec (fedcm maybe?), can we rename this repo to "digital-credentials"? 

The proposal talks about ["Digital Credential"](https://github.com/WICG/identity-credential/blob/main/digital-credentials-2-proposal.md).

**Comment by samuelgoto** [comment]
> "identity credentials" had been squatted by another spec (fedcm maybe?),

I wouldn't call it squatting, but yes, FedCM is built on top of the [`IdentityCredential`](https://fedidcg.github.io/FedCM/#browser-api-identity-credential-interface) type, and Chrome designed `IdentityCredential` to extend beyond federation ([this](https://github.com/fedidcg/FedCM/blob/main/meetings/2021/Web%20Identity%20API.pdf) should give you an idea of the use cases we are actively working on).

> an we rename this repo to "digital-credentials"?

I personally really like "Digital Credentials": it maps well to how the OpenID Foundation is organizing themselves to develop the OpenID4VP specs under the [Digital Credentials Working Group](https://openid.net/wg/digital-credentials-protocols/).

So, +1 from my side.

**Comment by marcoscaceres** [comment]
@samuelgoto wrote:

>I wouldn't call it squatting,

Apologies, it was a poor word choice.  

@TallTed, as I see it, there are multiple motivating factors for the change:

 * the repository's name is for the community (primarily CG members, eventually some WG) to easily find the work. I personally keep getting confused trying to find the thing and I'm trying to stop typing "identity-credential".  
 
Secondly, yes, there is the larger question of scope of the work: 

 * requesting an digital identity credential. 
 * The resulting "digital credential" (`DigitalCredential`). 

On the second point, I'd like to keep the generic "Digital Credential" because the `DigitalCredential` interface should be a generic platform primitive that represents any "digital credential" (we will be building up to this over the next few months or year(s)). 

As for the W3C part, this is not yet a "W3C" thing... its a "WICG" thing, which is denoted by the "WICG/" org... eventually we will move this to "W3C/digital-credential".

**Comment by marcoscaceres** [comment]
As agreed to on the call, renamed the repo to "digital-credentials". 

We can continue the more interesting questions around representing `DigitalCredentials` (as well as overlap with FedCM) as part of the spec development process and other issues.
