### ISSUE TITLE
Fold in Mobile Document Request API into spec, so we can do requests

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#67]
We should start looking at how to fold in the dictionaries of [mDoc request](https://github.com/WICG/digital-credentials/blob/main/mobile-document-request-api-proposal.md) into the spec.

**Comment by OR13** [comment]
I wonder if the HPKE part of this will consume https://www.iana.org/assignments/hpke/hpke.xhtml directly, or establish a new "named suites" registry specific to the protocol, like https://www.iana.org/assignments/mls/mls.xhtml#mls-ciphersuites

**Comment by Sakurann** [comment]
why do we need this if OID4VP supports mdocs?

**Comment by samuelgoto** [comment]
> why do we need this if OID4VP supports mdocs?

Because OID4VP doesn't (yet?) support the browser API?

**Comment by Sakurann** [comment]
The main thing that needs to be figured out on OID4VP front is how the OID4VP request over browser API looks like. I thought the agreement was to sort that out (still waiting for the issue/contribution in OID4VP repo). This feels like a diversion. 

also this is probably just terminology, but the framing of how browser api supports oid4vp feels more natural.

**Comment by samuelgoto** [comment]
@Sakurann lee kicked this off to get the ball rolling. Does this help?

https://github.com/openid/OpenID4VP/issues/90

**Comment by timcappalli** [comment]
Cleaning up old issues. This was addressed in OID4VP.
