### ISSUE TITLE
IdentityRequestProvider should be renamed something like "options" or "details"

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#70]
Although this is not "web observable" (because it's a dictionary), the [`IdentityRequestProvider`](https://wicg.github.io/digital-identities/#dom-identityrequestprovider) is not exactly about "providers"... it's more about what the provider need to match on. 

It might be good to rename the dictionary `IdentityRequestOptions` or `IdentityRequestDetails` or something...

**Comment by bc-pi** [comment]
Concur that `IdentityRequestOptions` or `IdentityRequestDetails` would better convey the intent of this thing. I must admit I was somewhat confused reading the [initial spec](https://github.com/WICG/digital-identities/pull/57) by the name of the thing "used to specify a request protocol and structured request" having the word "provider" in it, when [Identity credential provider](https://wicg.github.io/digital-identities/#dfn-identity-credential-provider) is seemingly the thing that answers such a request, not part of the request itself.

**Comment by marcoscaceres** [comment]
Sent #71 ... going with "details" because some members are mandatory.

**Comment by timcappalli** [comment]
@marcoscaceres @samuelgoto #71 is still open, but the current spec text uses `DigitalCredentialRequestOptions`. Are we sticking with that or still considering `IdentityRequestDetails`?

**Comment by samuelgoto** [comment]
I think [DigitalCredentialRequestOptions](https://wicg.github.io/digital-credentials/#the-digitalcredentialrequestoptions-dictionary) is correct in that it is the guidance from the credential management spec and consistent with all of the other credential types: 

- [FederatedCredentialRequestOptions](https://www.w3.org/TR/credential-management-1/#dictdef-federatedcredentialrequestoptions), 
- [PublicKeyCredentialRequestOptions](https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialrequestoptions), 
- [OTPCredentialRequestOptions](https://wicg.github.io/web-otp/#OTPCredentialRequestOptions) and 
- [IdentityCredentialRequestOptions](https://fedidcg.github.io/FedCM/#dictdef-identitycredentialrequestoptions).
