### ISSUE TITLE
Consume transient activation

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#91]
We should probably require to [consume transient activation](https://html.spec.whatwg.org/multipage/interaction.html#consume-user-activation) to call identity.get(), as it shows UI. 

Plus it would be otherwise annoying if sites could just pop up this dialog.

**Comment by RByers** [comment]
Agreed. Customers may have activation-less use cases (eg. click a button on one page that redirects to a different page where asking again would feel redundant). But I think we should start by requiring a tap/click and relax this only if there's a compelling use case.

**Comment by samuelgoto** [comment]
LGTM++

**Comment by marcoscaceres** [comment]
I think we want "[fully active descendant of a top-level traversable with user attention](https://html.spec.whatwg.org/multipage/interaction.html#fully-active-descendant-of-a-top-level-traversable-with-user-attention)"
